### ISSUE TITLE
Is made in electron

### ISSUE THREAD

**Issue by headassbtw** [harmonytf/HarmonyVPKTool#6]
Title

I'm not joking.

I'm also fully down to help rewrite it in a more sensible framework

**Comment by mrsteyk** [comment]
In what tho? There are not many things which cross compile easily. If you say Qt I will bully and you will cry in your bed

**Comment by barnabwhy** [comment]
wontfix :trollface:

**Comment by headassbtw** [comment]
> In what tho? 

ok now hear me out: 
imgui

it can look good with some theming and cross-compiles really easily
i have a project that uses it

**Comment by headassbtw** [comment]
threw this together in like ten minutes yesterday 

![E2F6078B-4797-4DB8-82FD-EFE6274287AD](https://user-images.githubusercontent.com/16214950/178721275-8d72517d-0f37-48ff-876e-4d7aedd67ce7.png)

**Comment by barnabwhy** [comment]
> > In what tho? 
> 
> ok now hear me out: 
> imgui
> 
> it can look good with some theming and cross-compiles really easily
> i have a project that uses it

okay so now please rewrite the lib in a different language or find some performant way to integrate js into your rewrite

**Comment by headassbtw** [comment]
aight, bet.

in all seriousness, if i do it, will you actually merge it lol

**Comment by barnabwhy** [comment]
> aight, bet.
> 
> in all seriousness, if i do it, will you actually merge it lol

no, but you will have just made a vpk tool to rival this one

**Comment by headassbtw** [comment]
the fuck makes you think i can compete

**Comment by barnabwhy** [comment]
> the fuck makes you think i can compete

you seemed pretty confident my guy

**Comment by headassbtw** [comment]
i’ve written tools before, nobody uses them, i can’t compete in terms of usage
albeit that past tool was half-baked

**Comment by mrsteyk** [comment]
> threw this together in like ten minutes yesterday 
> 
> 
> 
> ![E2F6078B-4797-4DB8-82FD-EFE6274287AD](https://user-images.githubusercontent.com/16214950/178721275-8d72517d-0f37-48ff-876e-4d7aedd67ce7.png)
> 
> 

Nice, meanwhile idk how one does layouts in this thing 🫡

**Comment by barnabwhy** [comment]
Bug fixed in upcoming v2 version.

**Comment by OctoNezd** [comment]
smh giving up on your original decisions
